apiVersion: 1

datasources:
  - name: Shelly-QuestDB
    type: questdb-questdb-datasource
    isDefault: true
    jsonData:
      server: questdb
      port: 8812
      username: admin
      password: quest
      tlsMode: disable
      maxOpenConnections: 100
      maxIdleConnections: 100
      maxConnectionLifetime: 14400
    secureJsonData:
      password: quest
